export function returnDummyData() {
  return [
    {
      spillested: "Det Akademiske Kvarter",
      spillestedid: "60",
      navn: "Tirsdagsimpro",
      sted: "Storelogen",
      longitude: "8.46895",
      latitude: "60.472",
      stedid: "9",
      arrid: "17467",
      eventlastchanged: "2020-02-25 11:34:07",
      dato: new Date().toISOString().substring(0, 10),
      datoslutt: new Date().toISOString().substring(0, 10),
      datostart: new Date().toISOString().substring(0, 10),
      datoshowto: new Date().toISOString().substring(0, 10),
      link: "https://www.linticket.no/page/no/60/-/17467",
      starttid: "18:00",
      slutttid: "20:00",
      arrangoernavn: "Studentteateret Immaturus",
      arrangoerid: "19",
      age: "0",
      tekst: "",
      teaser: "",
      typeid: "12",
      lengdegrad: "8.46895",
      breddegrad: "60.472",
      typenavn: "Øving",
    },
  ];
}
