# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kvarteret-preview

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_54ebe534dcb74efb8b1e170fc0fd0202 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_11ab6195d1aa40af8beb366e2b437c0f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_54ebe534dcb74efb8b1e170fc0fd0202 }}/dakit/kvarteretno:${{ github.sha }}
        file: ./Dockerfile.kvarteret

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kvarteret-preview'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6603541d977f42308d6936ad67cee284 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_54ebe534dcb74efb8b1e170fc0fd0202 }}/dakit/kvarteretno:${{ github.sha }}'